#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


# python /app/manage.py collectstatic --noinput
exec uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --proxy-headers --app-dir /app
